spring.application.name=HITL-Prototype
spring.datasource.url=jdbc:mysql://localhost:3306/hitl_db
spring.datasource.username=hitl_user
spring.datasource.password=hitl123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
server.port=8080